src/Orc/BookingBundle/Entity/Booking.php
<?php

namespace Orc\BookingBundle\Entity;

use Orc\BookingBundle\Entity\DateTime;
use Orc\BookingBundle\Entity\BookingStatus;
use Orc\BookingBundle\Entity\Crew;
use Orc\BookingBundle\Entity\Location;
use Orc\BookingBundle\Util\Slugify;
use Orc\BookingBundle\Validator\Constraints\Chronological;
use FOS\UserBundle\Entity\User;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Synd\MultiTenantBundle\Entity\TenantInterface;
use Synd\MultiTenantBundle\Entity\MultiTenantInterface;

/**
 * @Chronological(groups={"query"})
 * @ORM\Entity(repositoryClass="Orc\BookingBundle\Repository\BookingRepository")
 * @ORM\Table(name="booking")
 * @ORM\HasLifecycleCallbacks
 */
class Booking implements MultiTenantInterface
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="Orc\SaasBundle\Entity\Client")
     * @ORM\JoinColumn(name="client_id", referencedColumnName="id")
     */
    protected $client;

    /**
     * @Assert\Valid
     * @ORM\ManyToOne(targetEntity="Customer")
     */
    protected $customer;

    /**
     * @ORM\ManyToOne(targetEntity="Orc\UserBundle\Entity\User")
     * @ORM\JoinColumn(nullable=true)
     */
    protected $user;

    /**
     * @Assert\NotBlank(groups={"step2", "create"}, message="Please choose a service")
     * @ORM\ManyToOne(targetEntity="Service")
     * @ORM\JoinColumn(name="service_id", referencedColumnName="id", nullable=true)
     */
    protected $service;

    /**
     * @Assert\NotBlank(groups={"step3"}, message="Please choose a Time above")
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $dateStart;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $dateEnd;

    /**
     * @ORM\OneToOne(targetEntity="Location", cascade={"persist", "remove"})
     * @Assert\Valid
     */
    protected $location;

    /**
     * @ORM\ManyToOne(targetEntity="Crew")
     * @ORM\JoinColumn(name="crew_id", referencedColumnName="id", nullable=true)
     */
    protected $crew;

    /**
     * @ORM\ManyToOne(targetEntity="Region")
     * @ORM\JoinColumn(nullable=true, onDelete="SET NULL")
     */
    protected $region;

    /**
     * @ORM\Column(type="integer")
     */
    protected $status = BookingStatus::STATUS_ATTEMPT;

    /**
     * Service-Specific Answers
     * @ORM\OneToMany(targetEntity="BookingServiceField", mappedBy="booking", indexBy="slug", cascade={"persist", "remove"})
     * @Assert\Collection(
     *     fields = {
     *         "answer": {
     *             @Assert\NotBlank
     *         }
     *     },
     *     allowMissingFields = true,
     *     allowExtraFields = true,
     *     missingFieldsMessage = "Please answer all of the questions.",
     *     groups = {"step2"}
     * )
     */
    protected $fields;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $additionalInformation;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $notes;

    /**
     * @ORM\OneToMany(targetEntity="BookingNote", mappedBy="booking", cascade={"persist", "remove"})
     */
    protected $workerNotes;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $billed = false;

    /**
     * @ORM\OneToOne(targetEntity="CrewRadius", mappedBy="booking")
     * @ORM\JoinColumn(name="radius_id", onDelete="SET NULL")
     */
    protected $radius;

    /**
     * @ORM\Column(type="datetime")
     * @ORM\GeneratedValue
     */
    protected $datePosted;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $dateUpdated;

    protected $originalDates;

    protected $required;

    public function __construct()
    {
        $this->fields = new \Doctrine\Common\Collections\ArrayCollection();
        $this->workerNotes = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set dateStart
     *
     * @param datetime $dateStart
     * @return Booking
     */
    public function setDateStart(\DateTime $dateStart = null)
    {
        $this->dateStart = $dateStart;
        return $this;
    }

    /**
     * Get dateStart
     *
     * @return datetime
     */
    public function getDateStart()
    {
        return $this->dateStart;
    }

    /**
     * Set dateEnd
     *
     * @param datetime $dateEnd
     * @return Booking
     */
    public function setDateEnd(\DateTime $dateEnd = null)
    {
        $this->dateEnd = $dateEnd;
        return $this;
    }

    /**
     * Get dateEnd
     *
     * @return datetime
     */
    public function getDateEnd()
    {
        return $this->dateEnd;
    }

    /**
     * Set status
     *
     * @param integer $status
     * @return Booking
     */
    public function setStatus($status)
    {
        $validStatuses = BookingStatus::getStatuses();

        if (!isset($validStatuses[$status])) {
            throw new \InvalidArgumentException(sprintf('$status should be one of STATUS_* constants, "%s" given', $status));
        }

        $this->status = $status;
        return $this;
    }

    /**
     * Get status
     *
     * @return integer
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Get status text
     * @return   string
     */
    public function getStatusText()
    {
        $statuses = BookingStatus::getStatuses();
        return $statuses[$this->status];
    }

    /**
     * Set additionalInformation
     *
     * @param text $additionalInformation
     * @return Booking
     */
    public function setAdditionalInformation($additionalInformation)
    {
        $this->additionalInformation = $additionalInformation;
        return $this;
    }

    /**
     * Get additionalInformation
     *
     * @return text
     */
    public function getAdditionalInformation()
    {
        return $this->additionalInformation;
    }

    /**
     * Set billed
     *
     * @param boolean $billed
     * @return Booking
     */
    public function setBilled($billed)
    {
        $this->billed = $billed;
        return $this;
    }

    /**
     * Get billed
     *
     * @return boolean
     */
    public function getBilled()
    {
        return $this->billed;
    }

    /**
     * Set client
     *
     * @param Orc\SaasBundle\Entity\Client $client
     * @return Booking
     */
    public function setClient(\Orc\SaasBundle\Entity\Client $client = null)
    {
        $this->client = $client;
        return $this;
    }

    /**
     * Get client
     *
     * @return Orc\SaasBundle\Entity\Client
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * Set location
     *
     * @param Orc\BookingBundle\Entity\Location $location
     * @return Booking
     */
    public function setLocation(\Orc\BookingBundle\Entity\Location $location = null)
    {
        $this->location = $location;
        return $this;
    }

    /**
     * Get location
     *
     * @return Orc\BookingBundle\Entity\Location
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Set crew
     *
     * @param Orc\BookingBundle\Entity\Crew $crew
     * @return Booking
     */
    public function setCrew(\Orc\BookingBundle\Entity\Crew $crew = null)
    {
        $this->crew = $crew;
        return $this;
    }

    /**
     * Get crew
     *
     * @return Orc\BookingBundle\Entity\Crew
     */
    public function getCrew()
    {
        return $this->crew;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function updateTimestamps()
    {
        if (!$this->datePosted) {
            $this->datePosted = new DateTime();
        }

        $this->dateUpdated = new DateTime();
    }

    /**
     * Set datePosted
     *
     * @param datetime $datePosted
     * @return Booking
     */
    public function setDatePosted(\DateTime $datePosted)
    {
        $this->datePosted = $datePosted;
        return $this;
    }

    /**
     * Get datePosted
     *
     * @return datetime
     */
    public function getDatePosted()
    {
        return $this->datePosted;
    }

    /**
     * Set dateUpdated
     *
     * @param datetime $dateUpdated
     * @return Booking
     */
    public function setDateUpdated(\DateTime $dateUpdated)
    {
        $this->dateUpdated = $dateUpdated;
        return $this;
    }

    /**
     * Get dateUpdated
     *
     * @return datetime
     */
    public function getDateUpdated()
    {
        return $this->dateUpdated;
    }

    /**
     * Set service
     *
     * @param Orc\BookingBundle\Entity\Service $service
     * @return Booking
     */
    public function setService(\Orc\BookingBundle\Entity\Service $service = null)
    {
        $this->service = $service;
        return $this;
    }

    /**
     * Get service
     *
     * @return Orc\BookingBundle\Entity\Service
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Get fields
     *
     * @return Doctrine\Common\Collections\Collection
     */
    public function getFields()
    {
        return $this->fields;
    }

    /**
     * Set fields
     * @param    array      $fields
     */
    public function setFields($fields)
    {
        foreach ($fields as $key => $field) {
            $this->addField($field);
        }
    }

    /**
     * Add fields
     *
     * @param Orc\BookingBundle\Entity\BookingServiceField $fields
     * @return Booking
     */
    public function addField(\Orc\BookingBundle\Entity\BookingServiceField $field)
    {
        $field->setBooking($this);
        $this->fields->set($field->getSlug(), $field);

        return $this;
    }

    /**
     * Remove fields
     *
     * @param <variableType$fields
     */

src/Orc/BookingBundle/Form/Handler/Booking/CallbackHandler.php
<?php

namespace Orc\BookingBundle\Form\Handler\Booking;

use Orc\BookingBundle\Entity\Boundary;

use Orc\BookingBundle\Entity\BookingStatus;
use Orc\BookingBundle\Entity\Customer;
use Orc\BookingBundle\Entity\Booking;
use Orc\BookingBundle\Entity\Location;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\DependencyInjection\ContainerInterface;

class CallbackHandler
{
    protected $form;
    protected $request;
    protected $container;

    public function __construct(FormInterface $form, Request $request, ContainerInterface $container)
    {
        $this->form = $form;
        $this->request = $request;
        $this->container = $container;
    }

    public function process(Customer $customer, Booking $booking)
    {
        if (!$customer->getLocation() and $booking->getLocation()) {
            $customer->setLocation($this->cloneLocation($booking->getLocation()));
        }

        $this->form->setData($customer);

        if ($this->request->getMethod() == 'POST') {
            $this->form->bindRequest($this->request);

            if ($this->form->isValid()) {
                $this->onSuccess($customer, $booking);
                return true;
            }
        }

        return false;
    }

    protected function onSuccess(Customer $customer, Booking $booking)
    {
        $booking->setCustomer($customer);
        $booking->setStatus(BookingStatus::STATUS_REQUESTED);

        $cLocation = $booking->getCustomer()->getLocation();
        $cLocation->setAddress(sprintf('%s, %s, %s', $cLocation->getCode(), $cLocation->getCity(), $cLocation->getProvince()));


        if (!$booking->getLocation()) {
            $booking->setLocation($this->cloneLocation($customer->getLocation()));
        }

        $em = $this->container->get('doctrine.orm.entity_manager');
        $em->persist($customer);
        $em->persist($booking);
        $em->flush();

        if ($region = $this->getRegion($booking->getLocation())) {
            $booking->setRegion($region);
            $em->persist($booking);
            $em->flush();
        }

        $companyMailer = $this->container->get('orc_booking.mailer.notification');
        $companyMailer->send($booking);
    }

    /**
     * Converts a Location entity into [lat,lng] array
     * @param    Location
     * @return   array        [lat,lng]
     */
    protected function locationToCoordinates($location)
    {
        if ($location instanceof Boundary) {
            $location = $location->getLocation();
        }
        if (!$location instanceof Location) {
            throw new \InvalidArgumentException('$location must be a Location|Boundary');
        }

        return array($location->getLatitude(), $location->getLongitude());
    }

    /**
     * Gets the Region containing Location, if any
     * @param    Location
     * @return   Region|null
     */
    protected function getRegion(Location $location)
    {
        $pointInPolygon = $this->container->get('orc_booking.booking.inregion');
        $repository = $this->container->get('orc_booking.repository.region');

        $point = $this->locationToCoordinates($location);

        foreach ($repository->findAll() as $region) {
            $polygon = array_map(
                array($this, 'locationToCoordinates'),
                $region->getBoundaries()->toArray()
            );

            if ($pointInPolygon->inPolygon($point, $polygon)) {
                return $region;
            }
        }

        return false;
    }

    protected function cloneLocation(Location $clone)
    {
        $location = new Location;
        $location->setStreet($clone->getStreet());
        $location->setCity($clone->getCity());
        $location->setProvince($clone->getProvince());
        $location->setCountry($clone->getCountry());
        $location->setCode($clone->getCode());
        $location->setLatitude($clone->getLatitude());
        $location->setLongitude($clone->getLongitude());

        if ($clone->getQueryAddress()) {
            $location->setAddress($clone->getQueryAddress());
        }

        return $location;
    }
}

src/Orc/BookingBundle/Form/Handler/Booking/ConfirmLocationHandler.php
<?php

namespace Orc\BookingBundle\Form\Handler\Booking;

use Orc\BookingBundle\Form\Handler\Booking\LocationHandler;

class ConfirmLocationHandler extends LocationHandler
{
    public function process($data, $booking)
    {
        $this->form->setData($data);

        if ($this->request->getMethod() == 'POST') {
            $this->form->bindRequest($this->request);

            if ($this->form->isValid()) {
                $data->setKeepChanges(true);
                return $this->onSuccess($data, $booking);
            }
        }

        return false;
    }
}

src/Orc/BookingBundle/Form/Handler/Booking/CustomerHandler.php
<?php

namespace Orc\BookingBundle\Form\Handler\Booking;

use Orc\BookingBundle\Entity\BookingStatus;
use Orc\BookingBundle\Entity\Customer;
use Orc\BookingBundle\Entity\Booking;
use Orc\BookingBundle\Entity\Location;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\DependencyInjection\ContainerInterface;

class CustomerHandler
{
    protected $form;
    protected $request;
    protected $container;

    public function __construct(FormInterface $form, Request $request, ContainerInterface $container)
    {
        $this->form = $form;
        $this->request = $request;
        $this->container = $container;
    }

    public function process(Customer $customer, Booking $booking)
    {
        if (!$customer->getLocation()) {
            $customer->setLocation($this->cloneLocation($booking->getLocation()));
        }

        $this->form->setData($customer);

        if ($this->request->getMethod() == 'POST') {
            $this->form->bindRequest($this->request);

            if ($this->form->isValid()) {
                $this->onSuccess($customer, $booking);
                return true;
            }
        }

        return false;
    }

    protected function onSuccess(Customer $customer, Booking $booking)
    {
        $booking->setCustomer($customer);
        $booking->setStatus(BookingStatus::STATUS_ASSIGNED);

        $customer->getLocation()->setKeepChanges(true);
        $customer->getBilling()->getLocation()->setKeepChanges(true);

        $em = $this->container->get('doctrine.orm.entity_manager');
        $em->persist($customer);
        $em->persist($booking);
        $em->flush();

        $customerMailer = $this->container->get('orc_booking.mailer.confirmation');
        $customerMailer->send($booking);

        $companyMailer = $this->container->get('orc_booking.mailer.notification');
        $companyMailer->send($booking);

    }

    protected function cloneLocation(Location $clone)
    {
        $location = new Location;
        $location->setStreet($clone->getStreet());
        $location->setLine2($clone->getLine2());
        $location->setCity($clone->getCity());
        $location->setProvince($clone->getProvince());
        $location->setCountry($clone->getCountry());
        $location->setCode($clone->getCode());
        $location->setLatitude($clone->getLatitude());
        $location->setLongitude($clone->getLongitude());

        return $location;
    }
}

src/Orc/BookingBundle/Resources/views/Booking/edit-quick-readonly.html.twig
 <div class="modal hide fade" id="modal">
    <div id="quickEdit">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>
                {% if booking.complete %}
                    Delivered
                    {% if booking.dateCompleted %}
                        {{ booking.dateCompleted|date('Y-m-d') }}
                    {% endif %}
                {% endif %}
                {{ booking.name }} <small><strong>{{ booking.customer.name }}</strong> tel: <strong>{{ booking.customer.phone }}</strong></small>
            </h3>
        </div>
        <div class="modal-body">
        
            <div class="alert alert-warning">READ ONLY: This booking is in the past.</div>

            <p class="lead">
               Booked for {{ booking.crew ? booking.crew.name : "unassigned" }} from
               {{ booking.dateStart|timeShort }} to 
               {{ booking.dateEnd|timeShort }}
            </p>

            <p class="lead">Current Status: <strong>{{ booking.statusText }}</strong></p>

            <p>{{ booking.notes }}</p>

        </div>
        <div class="modal-footer">
            <p class="pull-left" style="padding-top: 6px;" tabindex="10"><i class="icon-eye-open"></i> <a href="{{ path('book_admin_edit',{id:booking.id}) }}">See all Booking details</a></p>
            
            {#
                <button type="submit" class="btn" tabindex="4"><i class="icon-retweet"></i> Rebook</button>
                <button type="submit" class="btn btn-success" tabindex="4"><i class="icon-leaf icon-white"></i> Mark as Billed</button>
            #}
        </div>
    </form>
</div>

src/Orc/BookingBundle/Resources/views/Booking/macros.html.twig
{% macro bookings_table(bookings) %}
    <table class="table">
        <tbody>
                {% for booking in bookings %}
                {% if booking.status %}
                <tr>
                    <td>{{ booking.name }}</td>

                    <td>
                        {% if booking.crew %}
                            {{ booking.crew.name }}
                        {% else %}
                            <em>unassigned</em>
                        {% endif %}
                    </td>
                       <td class="align-right">
                           <a class="btn btn-mini" href="{{ path('book_admin_edit', { 'id' : booking.id } ) }}" title="Booking Details"><i class="icon-eye-open"></i></a> 
                       </td>
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table> 
{% endmacro %}


{% macro bookings_list(bookings) %}
    {% for booking in bookings %}
        <tr>
            <td><a href="{{ path('book_admin_edit', { 'id' : booking.id } ) }}" title="Edit Booking">{{ booking.dateStart|date('m/d/Y \\a\\t H:ia') }}</a></td>
            <td>{{ booking.datePosted|date('m/d/Y \\a\\t H:ia') }}</td>
            <td>{{ booking.name }}</td>
            <td>
                {% if booking.crew %}
                    {{ booking.crew.name }}
                {% else %}
                    <em>unassigned</em>
                {% endif %}
            </td>
            <td>{{ booking.statusText }}</td>
        </tr>
    {% endfor %}
{% endmacro %}


{% macro booking_actions(booking, e) %}
    {# PRIMARY SAVE BUTTON #}       
    {% if not booking.id %}
        {% if booking.dateStart %}
            {{ _self.booking_button(e, 'place', 'Create Booking', 'file', 'primary') }}
        {% else %}
            {{ _self.booking_button(e, 'check', 'Check Availability', 'check', 'primary') }}
        {% endif %}
    {% else %}
         {{ _self.booking_button(e, 'update', 'Save Changes', 'file', 'primary') }}
    {% endif %}
    
    
    {# MISC BUTTONS #}
    {% if not booking.readOnly %}
        {% if booking.id and booking.statusText in ['Draft', 'Attempt', 'Requested', 'Cancelled'] and booking.region%}
            {{ _self.booking_button(e, booking.id ? 'reschedule' : 'check', 'Check Availability', 'check') }}
        {% endif %}
        {% if booking.statusText in ['Assigned', 'Unassignable'] and booking.region %}
            {{ _self.booking_button(e, 'reschedule', 'Reschedule', 'check') }}
        {% endif %}
        {% if not booking.id and booking.statusText in ['Assigned', 'Unassignable', 'Attempt', 'Requested'] %}
            {{ _self.booking_button(e, 'draft', 'Save as Draft', 'file') }}
        {% endif %}
    {% endif %}
    
    
    {# CANCEL / DELETE #}
    {% if booking.id and booking.statusText in ['Attempt', 'Requested', 'Draft'] %}
        <a class="btn btn-danger pull-right" href="{{ path('book_admin_delete', { id: booking.id }) }}">
            <i class="icon-minus-sign icon-white"></i>
            {% if booking.request %}
                Delete Request
            {% else %}
                Delete Booking
            {% endif %}
        </a>
    {% endif %}
    {% if booking.statusText in ['Assigned', 'Unassignable'] %}
        <a class="btn btn-danger pull-right" href="{{ path('book_admin_cancel', { id: booking.id }) }}">
            <i class="icon-minus-sign icon-white"></i>
            Cancel Booking
        </a>
    {% endif %}
    
    {% if e == 'test' %}
        <input type="submit" id="_submit">
    {% endif %}

{% endmacro %}


{% macro booking_button(e, value, label, icon, style, right) %}
    {# 
        behat can't submit the button value, so we're replacing with a radio 
        and a standard submit button
    #}

    {% set right = true %}
    {% spaceless %}
	    {% if e == 'test' %}
	        {{ _self.booking_radio_button(value, label) }}
	    {% else %}
	        {% set btnClass = 'btn' %}
	        {% set iconClass = 'icon-' ~ icon %}
	        
	        {% if style %}
	            {% set btnClass = btnClass ~ ' btn-' ~ style %}
	            {% set iconClass = iconClass ~ ' icon-white' %}
	        {% endif %}
	        
	        {% if right %}
	            {% set btnClass = btnClass ~ ' pull-right' %}
	        {% endif %}
	    
	        <button type="submit" class="{{ btnClass }}" name="save" value="{{ value }}">
	            <i class="{{ iconClass }}"></i> 
	            {{ label }}
	        </button>
	    {% endif %}
    {% endspaceless %}
{% endmacro %}

{% macro booking_radio_button(value, label) %}
    {% set id = "save_" ~ value %}
    <input type="radio" name="save" value="{{ value }}" id="{{ id }}">
    <label for="{{ id }}">{{ label }}</label>
{% endmacro %}

{% macro booking_summary(booking) %}
    <div class="summary">
        <h1>{{ booking.name }}</h1>
        <div>
            {{ booking.customer.name }}<br>
            {{ '%s %s, %s' | format(booking.customer.location.street, booking.customer.location.line2|trim, booking.customer.location.city) }}<br>
            {% if booking.customer.phone %}{{ booking.customer.phone }}<br>{% endif %}
            <br>
            Crew: {{ booking.crew ? booking.crew.name : 'unassigned' }}<br>
            Service: {{ booking.service.name }}<br>
            Region: {{ booking.region ? booking.region.name : 'outside service area' }}
        </div>
    </div>
{% endmacro %}

src/Orc/BookingBundle/Resources/views/Booking/search.html.twig
{% extends '::admin.html.twig' %}

{% block title %}Search Bookings{% endblock title %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="/vendors/jquery-ui-1.8.22/css/smoothness/jquery-ui-1.8.22.custom.css">

    <style>
        form.form-inline select {
            width: auto;
        }
    </style>
{% endblock stylesheets %}

{% block content %}
<header class="page-header">
    <a class="btn btn-large pull-right" href="{{ path('book_admin_create') }}"> <i class="icon-plus"></i> Create New Booking</a>
    <h1>Search Bookings</h1>
</header>   


{# TOP NAV #}
<div class="btn-group pull-right booking-views">
    <a href="{{ path('book_admin_view_day') }}" class="btn"><i class="icon-inbox"></i> Day</a>
    <a href="{{ path('book_admin_view_month') }}" class="btn"><i class="icon-calendar"></i> Month</a>
    <a href="{{ path('book_admin_view_list') }}" class="btn"><i class="icon-tasks"></i> List</a>
    <a href="{{ path('book_admin_search') }}" class="btn disabled"><i class="icon-search"></i> Search</a>
</div>

{# FORM FILTERS #}
<form method="post" class="form-inline">
	<fieldset>
	
	{{ form_errors(form) }}
	

    <div class="control-group">
	    <div class="controls">

            {{ form_widget(form.searchField) }}


            <div class="input-append">
                {{ form_widget(form.query, { attr: { class: 'search-query span4', 'placeholder': 'Search'} }) }}
                <button class="btn" type="submit"><i class="icon-search"></i></button>
            </div>
        </div>
    </div>


    <div class="control-group">                                             
        <div class="controls">
            <label class="control-label">Filters</label>

            {% spaceless %}
            <div class="input-prepend start">
                <span class="add-on"><i class="icon-calendar"></i></span>
                {{ form_widget(form.start, { attr: { class: 'search-query span2', placeholder: 'Start' } }) }}
            </div>
            {% endspaceless %}
            
            {% spaceless %}
            <div class="input-prepend end">
                <span class="add-on"> <i class="icon-calendar"></i></span>
                {{ form_widget(form.end, { attr: { class: 'search-query span2', placeholder: 'End' } }) }}
            </div>
            {% endspaceless %}

            {{ form_widget(form.status, { attr: { class: 'input-small' } }) }}

            {{ form_widget(form.region, { attr: { class: 'input-small' } }) }}

	    </div>
    </div>
	</fieldset>
	
	{{ form_rest(form) }}
</form>


{# BOOKINGS #}
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Street</th>
            <th>Region</th>
            <th>Status</th>
            <th>Date</th>
        </tr>
    </thead>
    <tbody>
        {% for booking in results %}
            <tr>
                <td><a href="{{ path('book_admin_edit', { 'id' : booking.id } ) }}" title="Edit {{ booking.name }}">{{ booking.customer.name }}</a></td>
                <td>{{ booking.customer.email }}</td>
                <td>{{ booking.customer.phone }}</td>
                <td>{{ booking.location.street }}</td>
                <td>{{ booking.region.name }}</td>
                <td>{{ booking.statusText }}</td>
                <td><a href="{{ path('book_admin_view_day', { date: booking.dateStart.format('Y-m-d'), booking: booking.id }) }}">{{ booking.dateStart|date('m/d/Y \\a\\t g:ia') }}</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table> 

{% endblock content %}

{% block javascript %}
    {{ parent() }}


    <script src="/vendors/jquery-ui-1.8.22/development-bundle/ui/jquery.ui.core.js"></script>
    <script src="/vendors/jquery-ui-1.8.22/development-bundle/ui/jquery.ui.widget.js"></script>
    <script src="/vendors/jquery-ui-1.8.22/development-bundle/ui/jquery.ui.datepicker.js"></script>

    <script>
        $(function() {
            $('.start input').datepicker({
                changeMonth: false,
                numberOfMonths: 2,
                dateFormat: "yy-mm-dd",
                onSelect: function( selectedDate ) {
                    $(".end input").datepicker( "option", "minDate", selectedDate );
                }
            });
            $('.end input').datepicker({
                changeMonth: false,
                numberOfMonths: 2,
                dateFormat: "yy-mm-dd",
                onSelect: function( selectedDate ) {
                    $('.start input').datepicker( "option", "maxDate", selectedDate );
                }
            });
        });
    </script>
{% endblock javascript %}